openapi: 3.0.1
info:
  title: Enterprise Resource Planning Manager
  description: API contract for the Enterprise Resource Planning Manager
  contact:
    name: DevOps Factory
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Generated server url
security:
  - BEARER_JWT: [ ]
tags:
  - name: user
    description: User resource.
paths:
  /users:
    post:
      tags:
        - user
      description: Create a new user.
      operationId: createUser
      responses:
        "200":
          $ref: '#/components/responses/UserDetailsResponse'
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "409":
          $ref: '#/components/responses/Conflict'
        "500":
          $ref: '#/components/responses/InternalServerError'
  /users/current-user:
    get:
      tags:
        - user
      description: Retrieve the current authenticated user’s details.
      operationId: getCurrentUser
      responses:
        "200":
          $ref: '#/components/responses/UserDetailsResponse'
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalServerError'
  /users/current-user/roles:
    get:
      tags:
        - user
      description: Retrieve the roles assigned to the current authenticated user.
      operationId: getCurrentUserRoles
      responses:
        "200":
          $ref: '#/components/responses/ListRolesResponse'
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    ApiError:
      required:
        - code
        - description
        - status
      type: object
      properties:
        status:
          type: integer
          format: int32
        code:
          type: string
        description:
          type: string
      description: General error response model.
    UserResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserModel'
    UserModel:
      type: object
      properties:
        userId:
          type: integer
          format: int64
        username:
          type: string
        givenName:
          type: string
        familyName:
          type: string
        email:
          type: string
        preferredLanguage:
          type: string
          example: en-US
      description: User model.
    RolesResponse:
      type: object
      properties:
        roles:
          type: array
          items:
            type: string
      description: List of roles.
  responses:
    UserDetailsResponse:
      description: Successfully retrieved user details.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserResponse'
    ListRolesResponse:
      description: Successfully retrieved list of roles.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/RolesResponse'
    BadRequest:
      description: The request was invalid or cannot be served. The exact error should be explained in the error payload.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    Unauthorized:
      description: Authentication is required and has failed or has not been provided.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    Forbidden:
      description: The request was valid, but the server is refusing action. The user might not have the necessary permissions for the resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    NotFound:
      description: The requested resource could not be found. This might be due to an incorrect URL or a non-existing resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    Conflict:
      description: The request could not be completed due to a conflict with the current state of the resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    InternalServerError:
      description: An error occurred on the server side. The request was valid but an unexpected condition was encountered.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
  securitySchemes:
    BEARER_JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT